export const dummyData = [
  {
    id: 185407,
    title: {
      english: "Takopi's Original Sin",
      native: "タコピーの原罪",
      romaji: "Takopii no Genzai",
      userPreferred: "Takopii no Genzai",
    },
    averageScore: 87,
    meanScore: 87,
    status: "FINISHED",
    nextAiringEpisode: null,
  },
  {
    id: 178788,
    title: {
      english: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
      native: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      romaji: "Kimetsu no Yaiba: Mugenjou-hen Movie 1 - Akaza Sairai",
      userPreferred: "Kimetsu no Yaiba: Mugenjou-hen Movie 1 - Akaza Sairai",
    },
    averageScore: 86,
    meanScore: 87,
    status: "FINISHED",
    nextAiringEpisode: null,
  },
  {
    id: 181444,
    title: {
      english: "The Fragrant Flower Blooms With Dignity",
      native: "薫る花は凛と咲く",
      romaji: "Kaoru Hana wa Rin to Saku",
      userPreferred: "Kaoru Hana wa Rin to Saku",
    },
    averageScore: 86,
    meanScore: 86,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757777400,
      episode: 11,
    },
  },
  {
    id: 182309,
    title: {
      english: "Grand Blue Dreaming Season 2",
      native: "ぐらんぶる Season 2",
      romaji: "Grand Blue Season 2",
      userPreferred: "Grand Blue Season 2",
    },
    averageScore: 83,
    meanScore: 84,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757950200,
      episode: 11,
    },
  },
  {
    id: 185660,
    title: {
      english: "DAN DA DAN Season 2",
      native: "ダンダダン 第2期",
      romaji: "Dandadan 2nd Season",
      userPreferred: "Dandadan 2nd Season",
    },
    averageScore: 83,
    meanScore: 83,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758209160,
      episode: 12,
    },
  },
  {
    id: 154768,
    title: {
      english: "My Dress-Up Darling Season 2",
      native: "その着せ替え人形は恋をする Season 2",
      romaji: "Sono Bisque Doll wa Koi wo Suru Season 2",
      userPreferred: "Sono Bisque Doll wa Koi wo Suru Season 2",
    },
    averageScore: 82,
    meanScore: 83,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757775600,
      episode: 11,
    },
  },
  {
    id: 175914,
    title: {
      english: "Call of the Night Season 2",
      native: "よふかしのうた Season 2",
      romaji: "Yofukashi no Uta Season 2",
      userPreferred: "Yofukashi no Uta Season 2",
    },
    averageScore: 82,
    meanScore: 83,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757687400,
      episode: 11,
    },
  },
  {
    id: 189117,
    title: {
      english: "Dr. STONE SCIENCE FUTURE Cour 2",
      native: "Dr.STONE SCIENCE FUTURE 2クール",
      romaji: "Dr. STONE: SCIENCE FUTURE Part 2",
      userPreferred: "Dr. STONE: SCIENCE FUTURE Part 2",
    },
    averageScore: 81,
    meanScore: 82,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758200400,
      episode: 11,
    },
  },
  {
    id: 171046,
    title: {
      english: "Rascal Does Not Dream of Santa Claus",
      native: "青春ブタ野郎はサンタクロースの夢を見ない",
      romaji: "Seishun Buta Yarou wa Santa Claus no Yume wo Minai",
      userPreferred: "Seishun Buta Yarou wa Santa Claus no Yume wo Minai",
    },
    averageScore: 80,
    meanScore: 81,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757773800,
      episode: 11,
    },
  },
  {
    id: 177689,
    title: {
      english: "The Summer Hikaru Died",
      native: "光が死んだ夏",
      romaji: "Hikaru ga Shinda Natsu",
      userPreferred: "Hikaru ga Shinda Natsu",
    },
    averageScore: 80,
    meanScore: 80,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757778960,
      episode: 10,
    },
  },
  {
    id: 151799,
    title: {
      english: "New PANTY & STOCKING with GARTERBELT",
      native: "New PANTY&STOCKING with GARTERBELT",
      romaji: "New PANTY & STOCKING with GARTERBELT",
      userPreferred: "New PANTY & STOCKING with GARTERBELT",
    },
    averageScore: 80,
    meanScore: 81,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758124800,
      episode: 11,
    },
  },
  {
    id: 178025,
    title: {
      english: "Gachiakuta",
      native: "ガチアクタ",
      romaji: "Gachiakuta",
      userPreferred: "Gachiakuta",
    },
    averageScore: 79,
    meanScore: 79,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757860200,
      episode: 10,
    },
  },
  {
    id: 179966,
    title: {
      english: "Secrets of the Silent Witch",
      native: "サイレント・ウィッチ 沈黙の魔女の隠しごと",
      romaji: "Silent Witch: Chinmoku no Majo no Kakushigoto",
      userPreferred: "Silent Witch: Chinmoku no Majo no Kakushigoto",
    },
    averageScore: 78,
    meanScore: 79,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757689200,
      episode: 10,
    },
  },
  {
    id: 186043,
    title: {
      english: "My Melody & Kuromi",
      native: "My Melody & Kuromi",
      romaji: "My Melody & Kuromi",
      userPreferred: "My Melody & Kuromi",
    },
    averageScore: 78,
    meanScore: 81,
    status: "FINISHED",
    nextAiringEpisode: null,
  },
  {
    id: 181841,
    title: {
      english: "CITY THE ANIMATION",
      native: "CITY THE ANIMATION",
      romaji: "CITY THE ANIMATION",
      userPreferred: "CITY THE ANIMATION",
    },
    averageScore: 78,
    meanScore: 79,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757862000,
      episode: 11,
    },
  },
  {
    id: 178754,
    title: {
      english: "Kaiju No. 8 Season 2",
      native: "怪獣８号 第２期",
      romaji: "Kaijuu 8-gou 2nd Season",
      userPreferred: "Kaijuu 8-gou 2nd Season",
    },
    averageScore: 78,
    meanScore: 78,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757772000,
      episode: 9,
    },
  },
  {
    id: 184237,
    title: {
      english: "SAKAMOTO DAYS Part 2",
      native: "SAKAMOTO DAYS 第２クール",
      romaji: "SAKAMOTO DAYS Part 2",
      userPreferred: "SAKAMOTO DAYS Part 2",
    },
    averageScore: 78,
    meanScore: 78,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757948400,
      episode: 11,
    },
  },
  {
    id: 189326,
    title: {
      english: "Toilet-Bound Hanako-kun Season 2 Part 2",
      native: "地縛少年花子くん２ 後編",
      romaji: "Jibaku Shounen Hanako-kun 2 Part 2",
      userPreferred: "Jibaku Shounen Hanako-kun 2 Part 2",
    },
    averageScore: 77,
    meanScore: 79,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757835000,
      episode: 11,
    },
  },
  {
    id: 177175,
    title: {
      english: "Arknights: RISE FROM EMBER",
      native: "アークナイツ 焔燼曙明",
      romaji: "Arknights: Enshin Shomei",
      userPreferred: "Arknights: Enshin Shomei",
    },
    averageScore: 76,
    meanScore: 77,
    status: "FINISHED",
    nextAiringEpisode: null,
  },
  {
    id: 178869,
    title: {
      english: "Clevatess",
      native: "クレバテス-魔獣の王と赤子と屍の勇者",
      romaji: "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha",
      userPreferred: "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha",
    },
    averageScore: 76,
    meanScore: 76,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758114000,
      episode: 12,
    },
  },
  {
    id: 180929,
    title: {
      english: "Ruri Rocks",
      native: "瑠璃の宝石",
      romaji: "Ruri no Houseki",
      userPreferred: "Ruri no Houseki",
    },
    averageScore: 76,
    meanScore: 77,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757853000,
      episode: 11,
    },
  },
  {
    id: 178090,
    title: {
      english:
        "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability Season 2",
      native: "転生したら第七王子だったので、気ままに魔術を極めます 第2期",
      romaji:
        "Tensei Shitara Dai Nana Ouji Dattanode, Kimamani Majutsu wo Kiwamemasu 2nd Season",
      userPreferred:
        "Tensei Shitara Dai Nana Ouji Dattanode, Kimamani Majutsu wo Kiwamemasu 2nd Season",
    },
    averageScore: 75,
    meanScore: 76,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758121200,
      episode: 11,
    },
  },
  {
    id: 178886,
    title: {
      english: "Dealing with Mikadono Sisters Is a Breeze",
      native: "帝乃三姉妹は案外、チョロい。",
      romaji: "Mikadono Sanshimai wa Angai, Choroi.",
      userPreferred: "Mikadono Sanshimai wa Angai, Choroi.",
    },
    averageScore: 74,
    meanScore: 75,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758122400,
      episode: 12,
    },
  },
  {
    id: 184591,
    title: {
      english: "There's No Freaking Way I'll Be Your Lover! Unless...",
      native:
        "わたしが恋人になれるわけないじゃん、ムリムリ! (※ムリじゃなかった!?)",
      romaji:
        "Watashi ga Koibito ni Nareru Wake Naijan, Murimuri! (※Muri ja Nakatta!?)",
      userPreferred:
        "Watashi ga Koibito ni Nareru Wake Naijan, Murimuri! (※Muri ja Nakatta!?)",
    },
    averageScore: 74,
    meanScore: 74,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757952000,
      episode: 11,
    },
  },
  {
    id: 185519,
    title: {
      english: "See You Tomorrow at the Food Court",
      native: "フードコートで、また明日。",
      romaji: "Food Court de, Mata Ashita.",
      userPreferred: "Food Court de, Mata Ashita.",
    },
    averageScore: 73,
    meanScore: 74,
    status: "FINISHED",
    nextAiringEpisode: null,
  },
  {
    id: 183127,
    title: {
      english: "Let's Go Karaoke!",
      native: "カラオケ行こ！",
      romaji: "Karaoke Iko!",
      userPreferred: "Karaoke Iko!",
    },
    averageScore: 73,
    meanScore: 76,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758803400,
      episode: 5,
    },
  },
  {
    id: 180425,
    title: {
      english: "With You and the Rain",
      native: "雨と君と",
      romaji: "Ame to Kimi to",
      userPreferred: "Ame to Kimi to",
    },
    averageScore: 71,
    meanScore: 73,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757781000,
      episode: 11,
    },
  },
  {
    id: 175035,
    title: {
      english: "Pokémon Concierge: Season 1: Part 2",
      native: "ポケモンコンシェルジュ 2クール",
      romaji: "Pokémon Concierge Part 2",
      userPreferred: "Pokémon Concierge Part 2",
    },
    averageScore: 71,
    meanScore: 76,
    status: "FINISHED",
    nextAiringEpisode: null,
  },
  {
    id: 173780,
    title: {
      english: "The Rising of the Shield Hero Season 4",
      native: "盾の勇者の成り上がり Season 4",
      romaji: "Tate no Yuusha no Nariagari Season 4",
      userPreferred: "Tate no Yuusha no Nariagari Season 4",
    },
    averageScore: 70,
    meanScore: 70,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758110400,
      episode: 11,
    },
  },
  {
    id: 189069,
    title: {
      english: "Milky☆Subway: The Galactic Limited Express",
      native: "銀河特急 ミルキー☆サブウェイ",
      romaji: "Ginga Tokkyuu Milky☆Subway",
      userPreferred: "Ginga Tokkyuu Milky☆Subway",
    },
    averageScore: 69,
    meanScore: 73,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758200040,
      episode: 12,
    },
  },
  {
    id: 179879,
    title: {
      english: "Betrothed to My Sister's Ex",
      native: "ずたぼろ令嬢は姉の元婚約者に溺愛される",
      romaji: "Zutaboro Reijou wa Ane no Moto Konyakusha ni Dekiai Sareru",
      userPreferred:
        "Zutaboro Reijou wa Ane no Moto Konyakusha ni Dekiai Sareru",
    },
    averageScore: 69,
    meanScore: 70,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757695980,
      episode: 11,
    },
  },
  {
    id: 186052,
    title: {
      english: "The Water Magician",
      native: "水属性の魔法使い",
      romaji: "Mizu Zokusei no Mahou Tsukai",
      userPreferred: "Mizu Zokusei no Mahou Tsukai",
    },
    averageScore: 68,
    meanScore: 69,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758212880,
      episode: 11,
    },
  },
  {
    id: 180460,
    title: {
      english: "Detectives These Days Are Crazy!",
      native: "まったく最近の探偵ときたら",
      romaji: "Mattaku Saikin no Tantei to Kitara",
      userPreferred: "Mattaku Saikin no Tantei to Kitara",
    },
    averageScore: 68,
    meanScore: 69,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758033000,
      episode: 12,
    },
  },
  {
    id: 185544,
    title: {
      english: "Welcome to the Outcast's Restaurant!",
      native: "追放者食堂へようこそ！",
      romaji: "Tsuihousha Shokudou e Youkoso!",
      userPreferred: "Tsuihousha Shokudou e Youkoso!",
    },
    averageScore: 67,
    meanScore: 68,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758207600,
      episode: 12,
    },
  },
  {
    id: 174188,
    title: {
      english: "Nukitashi THE ANIMATION",
      native: "ぬきたし THE ANIMATION",
      romaji: "Nukitashi THE ANIMATION",
      userPreferred: "Nukitashi THE ANIMATION",
    },
    averageScore: 67,
    meanScore: 68,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757696760,
      episode: 9,
    },
  },
  {
    id: 178433,
    title: {
      english:
        "Apocalypse Bringer Mynoghra: World Conquest Starts with the Civilization of Ruin",
      native: "異世界黙示録マイノグーラ ～破滅の文明で始める世界征服～",
      romaji:
        "Isekai Mokushiroku Mynoghra: Hametsu no Bunmei de Hajimeru Sekai Seifuku",
      userPreferred:
        "Isekai Mokushiroku Mynoghra: Hametsu no Bunmei de Hajimeru Sekai Seifuku",
    },
    averageScore: 67,
    meanScore: 67,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757856600,
      episode: 11,
    },
  },
  {
    id: 177887,
    title: {
      english: "Leviathan",
      native: "リヴァイアサン",
      romaji: "Leviathan",
      userPreferred: "Leviathan",
    },
    averageScore: 66,
    meanScore: 68,
    status: "FINISHED",
    nextAiringEpisode: null,
  },
  {
    id: 178675,
    title: {
      english: "Bad Girl",
      native: "ばっどがーる",
      romaji: "Bad Girl",
      userPreferred: "Bad Girl",
    },
    averageScore: 66,
    meanScore: 67,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757775600,
      episode: 11,
    },
  },
  {
    id: 179828,
    title: {
      english: "A Couple of Cuckoos Season 2",
      native: "カッコウの許嫁 Season2",
      romaji: "Kakkou no Iinazuke Season 2",
      userPreferred: "Kakkou no Iinazuke Season 2",
    },
    averageScore: 66,
    meanScore: 67,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758031200,
      episode: 11,
    },
  },
  {
    id: 177474,
    title: {
      english: "TOUGEN ANKI",
      native: "桃源暗鬼",
      romaji: "Tougen Anki",
      userPreferred: "Tougen Anki",
    },
    averageScore: 66,
    meanScore: 66,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757685600,
      episode: 10,
    },
  },
  {
    id: 180794,
    title: {
      english: "Cultural Exchange with a Game Centre Girl",
      native: "ゲーセン少女と異文化交流",
      romaji: "GaCen Shoujo to Ibunka Kouryuu",
      userPreferred: "GaCen Shoujo to Ibunka Kouryuu",
    },
    averageScore: 64,
    meanScore: 65,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757860200,
      episode: 10,
    },
  },
  {
    id: 195517,
    title: {
      english: null,
      native: "SUGAR SUGAR RUNE: Les deux sorcières",
      romaji: "SUGAR SUGAR RUNE: Les deux sorcières",
      userPreferred: "SUGAR SUGAR RUNE: Les deux sorcières",
    },
    averageScore: 64,
    meanScore: 71,
    status: "FINISHED",
    nextAiringEpisode: null,
  },
  {
    id: 155838,
    title: {
      english: "New Saga",
      native: "強くてニューサーガ",
      romaji: "Tsuyokute New Saga",
      userPreferred: "Tsuyokute New Saga",
    },
    averageScore: 63,
    meanScore: 64,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758129360,
      episode: 12,
    },
  },
  {
    id: 156395,
    title: {
      english: null,
      native: "ブスに花束を。",
      romaji: "Busu ni Hanataba wo.",
      userPreferred: "Busu ni Hanataba wo.",
    },
    averageScore: 63,
    meanScore: 65,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757683800,
      episode: 11,
    },
  },
  {
    id: 186003,
    title: {
      english: "Fermat Kitchen",
      native: "フェルマーの料理",
      romaji: "Fermat no Ryouri",
      userPreferred: "Fermat no Ryouri",
    },
    averageScore: 63,
    meanScore: 65,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757773800,
      episode: 10,
    },
  },
  {
    id: 185755,
    title: {
      english: "Puniru is a Kawaii Slime Season 2",
      native: "ぷにるはかわいいスライム 第2期",
      romaji: "Puniru wa Kawaii Slime 2nd Season",
      userPreferred: "Puniru wa Kawaii Slime 2nd Season",
    },
    averageScore: 62,
    meanScore: 68,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757838600,
      episode: 11,
    },
  },
  {
    id: 185965,
    title: {
      english: "Solo Camping for Two",
      native: "ふたりソロキャンプ",
      romaji: "Futari Solo Camp",
      userPreferred: "Futari Solo Camp",
    },
    averageScore: 62,
    meanScore: 63,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758209400,
      episode: 11,
    },
  },
  {
    id: 169440,
    title: {
      english: "Reborn as a Vending Machine, I Now Wander the Dungeon Season 2",
      native: "自動販売機に生まれ変わった俺は迷宮を彷徨う 2nd Season",
      romaji:
        "Jidou Hanbaiki ni Umarekawatta Ore wa Meikyuu wo Samayou 2nd Season",
      userPreferred:
        "Jidou Hanbaiki ni Umarekawatta Ore wa Meikyuu wo Samayou 2nd Season",
    },
    averageScore: 62,
    meanScore: 62,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1758114000,
      episode: 12,
    },
  },
  {
    id: 170113,
    title: {
      english: "Private Tutor to the Duke's Daughter",
      native: "公女殿下の家庭教師",
      romaji: "Koujo Denka no Katei Kyoushi",
      userPreferred: "Koujo Denka no Katei Kyoushi",
    },
    averageScore: 61,
    meanScore: 61,
    status: "RELEASING",
    nextAiringEpisode: {
      airingAt: 1757781000,
      episode: 11,
    },
  },
  {
    id: 179678,
    title: {
      english: "Hell Teacher: Jigoku Sensei Nube (2025)",
      native: "地獄先生ぬ～べ～ (2025)",
      romaji: "Jigoku Sensei Nube (2025)",
      userPreferred: "Jigoku Sensei Nube (2025)",
    },
    averageScore: 61,
    meanScore: 63,
    status: "RELEASING",
    nextAiringEpisode: null,
  },
];
